version: '3.8'
services:
  app:
    build: .
    command: make start
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    restart: always
    command: make build
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgres
    ports:
      - "5434:5432"