services:
  app:
    build: .
    command: make start
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
#      - /var/lib/postgres
#    ports:
#      - "5435:5432"